<?php

namespace Database\Seeders;

use App\Models\Kehadiran;
use Illuminate\Database\Seeder;

class KehadiranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-10",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Pertama',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-10",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Pertama',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-11",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Kedua',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-11",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Kedua',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-12",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Ketiga',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-12",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Ketiga',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-13",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Keempat',
        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-13",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Keempat',

        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-14",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Kelima',

        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-14",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Kelima',

        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-15",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
            'jadual_kursus_ref' => 'Keenam',

        ]);
        Kehadiran::create([
            'kod_kursus' => "01",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-15",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
            'jadual_kursus_ref' => 'Keenam',
        ]);

        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-10",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-10",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-11",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-11",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-12",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-12",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-13",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-13",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-14",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-14",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-15",
            'masa' => "9-10",
            'jadual_kursus_id' => "1",
            'sesi' => "1",
        ]);
        Kehadiran::create([
            'kod_kursus' => "02",
            'kod_jenis_kursus' => "LUARAN",
            'kod_kategori' => "1",
            'id_pekebun_kecil' => "",
            'no_pekerja' => "2",
            'status_kehadiran' => "",
            'alasan_ketidakhadiran' => "",
            'nama_pengganti' => "",
            'noKP_pengganti' => "",
            'tarikh' => "2022-01-15",
            'masa' => "11-12",
            'jadual_kursus_id' => "1",
            'sesi' => "2",
        ]);

    }
}
